"use client";

import { useState } from "react";
import RulesetConfig, { useRulesetConfig } from "@/components/RulesetConfig";

interface VideoContent {
  title: string;
  script: string;
  storyboard: string;
  keyPoints: string[];
  duration: string;
  principle: string;
  thumbnailImage?: string;
  imagePrompt?: string;
  storyboardImages?: Array<{
    scene: number;
    description: string;
    imageUrl: string;
    imagePrompt: string;
  }>;
  videoUrl?: string;
}

const principles = [
  {
    id: "ethicalFoundation",
    icon: "🌱",
    title: "Ethical Foundation",
    description: "Code that promotes fairness and responsible AI development",
  },
  {
    id: "biasAwareness",
    icon: "⚖️",
    title: "Bias Awareness",
    description: "Detect and prevent biases that AI systems might inherit",
  },
  {
    id: "safetyFirst",
    icon: "🛡️",
    title: "Safety First",
    description: "Prioritize security, error handling, and safe defaults",
  },
  {
    id: "responsibleDesign",
    icon: "📚",
    title: "Responsible Design",
    description: "Consider long-term impact on AI systems and users",
  },
];

export default function VideoPage() {
  const [selectedPrinciple, setSelectedPrinciple] = useState<string | null>(null);
  const [videoContent, setVideoContent] = useState<VideoContent | null>(null);
  const [loading, setLoading] = useState(false);
  const [videoType, setVideoType] = useState<"educational" | "tutorial" | "demo">("educational");
  const [generateMedia, setGenerateMedia] = useState(false);
  const rulesets = useRulesetConfig();

  const generateVideo = async () => {
    if (!selectedPrinciple) {
      alert("Please select an AI Parenting principle");
      return;
    }

    setLoading(true);
    setVideoContent(null);

    try {
      const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'}/api/video/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          principle: selectedPrinciple,
          videoType,
          generateMedia,
          rulesets: {
            ethicalFoundation: rulesets.ethicalFoundation,
            biasAwareness: rulesets.biasAwareness,
            safetyFirst: rulesets.safetyFirst,
            responsibleDesign: rulesets.responsibleDesign,
          }
        }),
      });

      const data = await response.json();
      setVideoContent(data);
    } catch (error) {
      alert("Error generating video content. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    alert("Copied to clipboard!");
  };

  const exportScript = () => {
    if (!videoContent) return;
    
    const content = `# ${videoContent.title}

## Principle: ${videoContent.principle}
## Duration: ${videoContent.duration}
## Type: ${videoType}

## Key Points:
${videoContent.keyPoints.map((point, i) => `${i + 1}. ${point}`).join("\n")}

## Video Script:

${videoContent.script}

## Storyboard:

${videoContent.storyboard}

---
Generated by Covibe.ai - AI Parenting for Code
`;
    
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${selectedPrinciple}-video-script.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Header */}
      <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 p-4 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2">
              <span>🎬</span> AI Parenting Video Generator
            </h1>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Generate educational videos for AI Parenting principles
            </p>
          </div>
          <a
            href="/"
            className="px-4 py-2 bg-gray-100 dark:bg-gray-700 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600"
          >
            ← Home
          </a>
        </div>
      </div>

      <div className="max-w-7xl mx-auto p-6">
        {/* Ruleset Config */}
        <div className="mb-6">
          <RulesetConfig compact />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Input Panel */}
          <div className="space-y-4">
            <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6">
              <h2 className="text-lg font-semibold mb-4">Select Principle & Type</h2>

              <div className="space-y-4">
                {/* Principle Selection */}
                <div>
                  <label className="block text-sm font-medium mb-3">AI Parenting Principle *</label>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {principles.map((principle) => (
                      <button
                        key={principle.id}
                        onClick={() => setSelectedPrinciple(principle.id)}
                        className={`p-4 rounded-lg border-2 text-left transition-all ${
                          selectedPrinciple === principle.id
                            ? "border-blue-500 bg-blue-50 dark:bg-blue-900/20"
                            : "border-gray-200 dark:border-gray-600 hover:border-gray-300 dark:hover:border-gray-500"
                        }`}
                      >
                        <div className="text-2xl mb-2">{principle.icon}</div>
                        <div className="font-medium">{principle.title}</div>
                        <div className="text-xs text-gray-600 dark:text-gray-400 mt-1">
                          {principle.description}
                        </div>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Video Type Selection */}
                <div>
                  <label className="block text-sm font-medium mb-3">Video Type</label>
                  <div className="grid grid-cols-3 gap-2">
                    {[
                      { id: "educational", label: "📚 Educational", desc: "Explain concepts" },
                      { id: "tutorial", label: "🎓 Tutorial", desc: "Step-by-step guide" },
                      { id: "demo", label: "💻 Demo", desc: "Code examples" },
                    ].map((type) => (
                      <button
                        key={type.id}
                        onClick={() => setVideoType(type.id as any)}
                        className={`p-3 rounded-lg border-2 text-center transition-all ${
                          videoType === type.id
                            ? "border-blue-500 bg-blue-50 dark:bg-blue-900/20"
                            : "border-gray-200 dark:border-gray-600 hover:border-gray-300"
                        }`}
                      >
                        <div className="font-medium text-sm">{type.label}</div>
                        <div className="text-xs text-gray-600 dark:text-gray-400 mt-1">
                          {type.desc}
                        </div>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Generate Media Option */}
                <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
                  <label className="flex items-center gap-3 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={generateMedia}
                      onChange={(e) => setGenerateMedia(e.target.checked)}
                      className="w-5 h-5 text-blue-600 rounded focus:ring-blue-500"
                    />
                    <div>
                      <div className="font-medium text-sm">🎨 Generate Images & Video</div>
                      <div className="text-xs text-gray-600 dark:text-gray-400">
                        Create actual images and video (requires image/video generation API keys)
                      </div>
                    </div>
                  </label>
                </div>

                <button
                  onClick={generateVideo}
                  disabled={loading || !selectedPrinciple}
                  className="w-full px-6 py-3 bg-blue-500 text-white rounded-lg hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed font-medium"
                >
                  {loading ? "Generating Video Content..." : "🎬 Generate Video Content"}
                </button>
              </div>
            </div>

            {/* Info */}
            <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
              <h3 className="font-semibold mb-2 flex items-center gap-2">
                <span>💡</span> About Video Generation
              </h3>
              <ul className="text-sm text-gray-700 dark:text-gray-300 space-y-1 list-disc list-inside">
                <li>Generates complete video scripts and storyboards</li>
                <li>Includes key talking points and visual descriptions</li>
                <li>Ready to use with video production tools</li>
                <li>Export scripts for video editing software</li>
              </ul>
            </div>
          </div>

          {/* Results Panel */}
          <div className="space-y-4">
            {videoContent && (
              <>
                {/* Video Overview */}
                <div className="bg-gradient-to-br from-purple-500 to-pink-600 rounded-lg p-6 text-white">
                  <div className="flex items-center justify-between mb-4">
                    <div>
                      <div className="text-sm opacity-90 mb-1">Generated Video</div>
                      <div className="text-2xl font-bold">{videoContent.title}</div>
                      <div className="text-sm opacity-90 mt-1">
                        {videoContent.duration} • {videoContent.principle}
                      </div>
                    </div>
                    <button
                      onClick={exportScript}
                      className="px-4 py-2 bg-white/20 hover:bg-white/30 rounded-lg text-sm font-medium"
                    >
                      💾 Export
                    </button>
                  </div>
                  
                  {/* Thumbnail Image */}
                  {videoContent.thumbnailImage && (
                    <div className="mt-4">
                      <img
                        src={videoContent.thumbnailImage}
                        alt="Video thumbnail"
                        className="w-full rounded-lg border-2 border-white/20"
                      />
                    </div>
                  )}
                  
                  {/* Generated Video */}
                  {videoContent.videoUrl && (
                    <div className="mt-4">
                      <video
                        src={videoContent.videoUrl}
                        controls
                        className="w-full rounded-lg border-2 border-white/20"
                      >
                        Your browser does not support the video tag.
                      </video>
                    </div>
                  )}
                </div>

                {/* Key Points */}
                <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6">
                  <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
                    <span>📌</span> Key Points
                  </h3>
                  <ul className="space-y-2">
                    {videoContent.keyPoints.map((point, idx) => (
                      <li
                        key={idx}
                        className="flex items-start gap-2 text-sm text-gray-700 dark:text-gray-300"
                      >
                        <span className="text-blue-500 mt-1">•</span>
                        <span>{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Script */}
                <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6">
                  <div className="flex items-center justify-between mb-3">
                    <h3 className="text-lg font-semibold flex items-center gap-2">
                      <span>📝</span> Video Script
                    </h3>
                    <button
                      onClick={() => copyToClipboard(videoContent.script)}
                      className="px-3 py-1 text-sm bg-gray-100 dark:bg-gray-700 rounded hover:bg-gray-200 dark:hover:bg-gray-600"
                    >
                      📋 Copy
                    </button>
                  </div>
                  <div className="prose dark:prose-invert max-w-none">
                    <div className="text-gray-700 dark:text-gray-300 whitespace-pre-wrap leading-relaxed">
                      {videoContent.script}
                    </div>
                  </div>
                </div>

                {/* Storyboard */}
                <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6">
                  <div className="flex items-center justify-between mb-3">
                    <h3 className="text-lg font-semibold flex items-center gap-2">
                      <span>🎨</span> Storyboard
                    </h3>
                    <button
                      onClick={() => copyToClipboard(videoContent.storyboard)}
                      className="px-3 py-1 text-sm bg-gray-100 dark:bg-gray-700 rounded hover:bg-gray-200 dark:hover:bg-gray-600"
                    >
                      📋 Copy
                    </button>
                  </div>
                  <div className="prose dark:prose-invert max-w-none">
                    <div className="text-gray-700 dark:text-gray-300 whitespace-pre-wrap leading-relaxed">
                      {videoContent.storyboard}
                    </div>
                  </div>
                  
                  {/* Storyboard Images */}
                  {videoContent.storyboardImages && videoContent.storyboardImages.length > 0 && (
                    <div className="mt-6">
                      <h4 className="font-semibold mb-3">Visual Storyboard</h4>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {videoContent.storyboardImages.map((scene, idx) => (
                          <div key={idx} className="border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden">
                            {scene.imageUrl ? (
                              <img
                                src={scene.imageUrl}
                                alt={`Scene ${scene.scene}`}
                                className="w-full h-48 object-cover"
                              />
                            ) : (
                              <div className="w-full h-48 bg-gray-100 dark:bg-gray-700 flex items-center justify-center">
                                <span className="text-gray-400">Image generating...</span>
                              </div>
                            )}
                            <div className="p-3">
                              <div className="text-sm font-medium mb-1">Scene {scene.scene}</div>
                              <div className="text-xs text-gray-600 dark:text-gray-400">
                                {scene.description}
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
                
                {/* Image Prompt (if available) */}
                {videoContent.imagePrompt && (
                  <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6">
                    <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
                      <span>🖼️</span> Image Generation Prompt
                    </h3>
                    <div className="bg-gray-50 dark:bg-gray-900 p-4 rounded-lg">
                      <p className="text-sm text-gray-700 dark:text-gray-300">
                        {videoContent.imagePrompt}
                      </p>
                      <button
                        onClick={() => copyToClipboard(videoContent.imagePrompt || "")}
                        className="mt-2 px-3 py-1 text-xs bg-gray-200 dark:bg-gray-700 rounded hover:bg-gray-300 dark:hover:bg-gray-600"
                      >
                        📋 Copy Prompt
                      </button>
                    </div>
                  </div>
                )}
              </>
            )}

            {/* Empty State */}
            {!videoContent && !loading && (
              <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-12 text-center">
                <div className="text-6xl mb-4">🎬</div>
                <p className="text-gray-600 dark:text-gray-400">
                  Select a principle and generate video content
                </p>
              </div>
            )}

            {/* Loading State */}
            {loading && (
              <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-12 text-center">
                <div className="text-6xl mb-4 animate-pulse">🎬</div>
                <p className="text-gray-600 dark:text-gray-400">
                  Generating video content...
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
